{% set name = "taturtle" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: .

requirements:
  host:
    - python
    - numpy
    - scikit-image
    - tifffile
    - scipy
    - multiprocessing
  run:
    - python
    - numpy
    - scikit-image
    - tifffile
    - scipy
    - multiprocessin

test:
  imports:
    - TATURTLE
  commands:
    - python -m unittest discover -s test

about:
  home: https://github.com/vib-bic-code/taturtle.git
  license: BSD-3-Clause
  license_family: BSD
  summary: Alignment of FIB-SEM images using template matching and thickness correction.

extra:
  recipe-maintainers:
    - tatianawllr